//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWiki.DataProvider.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class User
    {
        /// <summary>
        /// The anonymous user.
        /// </summary>
        public static User Anonymous = new User { UserID = -1, UserName = "anonymous", Roles = new Role[] { Role.AnonymousRole }, Email = "" };

        public User()
        {
            this.Groups = new HashSet<Group>();
            this.UserFriends = new HashSet<UserFriend>();
            this.Roles = new HashSet<Role>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int UserID { get; set; }

        [MaxLength(30)]
        public string UserName { get; set; }

        [MaxLength(128)]
        public string HashPwd { get; set; }

        [MaxLength(30)]
        public string Email { get; set; }

        [Required]
        public DateTime RegTime { get; set; }
        
        /// <summary>
        /// for third part login.
        /// </summary>
        public string Provider { get; set; }

        /// <summary>
        /// for third part login
        /// </summary>
        [MaxLength(100)]
        public string ProviderUserID { get; set; }

        public virtual ICollection<Group> Groups { get; set; }

        public virtual UserAppend UserAppend { get; set; }
        public virtual ICollection<UserFriend> UserFriends { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
    }
}
