//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWiki.DataProvider.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("UserAppend")]
    public class UserAppend
    {
        [Key, ForeignKey("User")]
        public int UserID { get; set; }

        [MaxLength(30)]
        public string NickName { get; set; }

        [MaxLength(100)]
        public string Question01 { get; set; }

        [MaxLength(30)]
        public string Answer01 { get; set; }

        [MaxLength(100)]
        public string Question02 { get; set; }

        [MaxLength(30)]
        public string Answer02 { get; set; }

        [MaxLength(30)]
        public string RealName { get; set; }

        public Nullable<int> Sex { get; set; }

        [MaxLength(255)]
        public string HeadImage { get; set; }

        public Nullable<System.DateTime> Birthday { get; set; }

        [MaxLength(300)]
        public string Spaceurl01 { get; set; }

        [MaxLength(300)]
        public string Spaceurl02 { get; set; }

        [MaxLength(160)]
        public string Hobits { get; set; }
        [MaxLength(30)]
        public string Country { get; set; }
        [MaxLength(20)]
        public string Province { get; set; }
        [MaxLength(20)]
        public string City { get; set; }
        [MaxLength(12)]
        public string Phone1 { get; set; }
        [MaxLength(12)]
        public string Phone2 { get; set; }
        [MaxLength(120)]
        public string Address { get; set; }
    
        public virtual User User { get; set; }
    }
}
